name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Scan de sécurité
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Analyse de vulnérabilités avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ubuntu:22.04"
          format: "table"

  build-and-test:
    name: Build et Tests
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      
      - name: Build de l’image Docker
        run: docker-compose -f .devcontainer/docker-compose.yml build

      - name: Exécuter les tests unitaires
        run: docker-compose -f .devcontainer/docker-compose.yml run dev-env bash -c "cd /workspace/src && python3 -m unittest discover"

      - name: Tester la capture d’image
        run: docker-compose -f .devcontainer/docker-compose.yml run dev-env bash -c "python3 /workspace/src/capture_image_logging.py && ls -l /workspace/src/images/ && cat /workspace/src/logs/simulation.log"

