services:
  dev-env:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "5901:5901"
    environment:
      - DISPLAY=:1
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
